# Generated by Django 4.2.9 on 2026-09-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_id', models.CharField(max_length=64, unique=True, verbose_name='验证码ID')),
                ('code', models.CharField(max_length=8, verbose_name='验证码')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'db_table': 'ops_captcha',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginFailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('fail_count', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('last_fail_at', models.DateTimeField(auto_now=True, verbose_name='最后失败时间')),
            ],
            options={
                'verbose_name': '登录失败记录',
                'verbose_name_plural': '登录失败记录',
                'db_table': 'ops_login_fail',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('value', models.CharField(max_length=200, verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'ops_config',
            },
        ),
    ]
